 - name: catalogue configure
   hosts: catalogue
   become: yes
   tasks:
   - name: disable nodejs current version
     ansible.builtin.command: dnf module disable nodejs -y

   - name: enable nodejs 20 version
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: install nodejs
     ansible.builtin.dnf:
      name: nodejs
      state: present

   - name: create system user roboshop
     ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system user"

   - name: delete app directory
     ansible.builtin.file:
      path: /app
      state: absent

   - name: create directory
     ansible.builtin.file:
      path: /app
      state: directory

   - name: delete user zip file
     ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

   - name: download catalogue
     ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

   - name: unarchive catalogue
     ansible.builtin.unarchive:
       src: /tmp/catalogue.zip
       dest: /app
       remote_src: yes

   - name: download the npm dependencies
     community.general.npm:
      path: /app

   - name: copy catalogue service
     ansible.builtin.template:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

   - name: reload the catalogue
     ansible.builtin.systemd_service:
      daemon_reload: true

   - name: copy mongo repo
     ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

   - name: install  mongodb-mongosh client
     ansible.builtin.dnf:
     name:  mongodb-mongosh
     state: present

   - name: check catalogue products loaded
     ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
     register: catalogue_output

   - name: print the ec2_output
     ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

   - name: load the catalogue products
     ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
     when: catalogue_output.stdout  | int < 0

   - name: enabled and start the catalogue
     ansible.builtin.service:
      name: catalogue
      enabled: yes
      state: restarted

  