- name: frontend configure
  hosts: frontend
  become: yes
  tasks:
  - name: disable nginx version
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable nginx:1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: remove default nginx content
    ansible.builtin.file:
      path: /usr/share/nginx/html/* 
      state: absent

  - name: create nginx default content
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: directory

  - name: download the nginx code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unarchive the nginx zip file
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html

  - name: copy the nginx conf
    ansible.builtin.template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: restarted