- name: payment configure
  hosts:  payment
  become: yes
  tasks:
  - name: install  phyton3
    ansible.builtin.dnf:
      name: 
      - python3 
      - gcc 
      - python3-devel
      state: present

  - name: create systemuser roboshop
    ansible.builtin.user:
      name: roboshop
      system: tru
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system user"

  - name: delete directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete zip file
    ansible.builtin.file:
      path: /tmp/payment.zip
      state: absent

  - name: download payment code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
      dest: /tmp/payment.zip

  - name: unarchive the zip file
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: install pip requirement dependencies
    ansible.builtin.pip:
      requirements: /app/requirements.txt
      executable: pip3

  - name: copy the payment service
    ansible.builtin.template:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: reload the payment service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable payment
    ansible.builtin.service:
      name: payment
      enabled: yes
      state: restarted
