- name: rabbitmq configure
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy the rabbitmq repo
    ansible.builtin.template:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install rabbitmq
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present

  - name: add rabbitmq aplication user
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123
    ignore_errors: yes

  - name: set permissions to the user
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

  - name: start and enable rabbitmq
    ansible.builtin.service:
      name: rabbitmq-server
      state: restarted
      enabled: yes

















