- name: create instance and r53 records
  hosts: all
  connection: local
  vars:
  sg_id: sg-05d7b78f97f2eb219
  ami_id: ami-0220d79f3f480ecf5
  environment: dev
  instances:
  - mongodb
  - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
    security_group: "{{ sg_id }}"
    image_id: "{{ ami_id }}"
    name: "{{ item }}-{{ environment }}"
    tags:
    Project: roboshop
    Component: "{{ item }}"
    Environment: "{{ environment }}"
    Name: "{{ item }}-{{ environment }}"
  loops: "{{ instances }}"
  register: ec2_output

  -name: print the ec2_output
  ansible.builtin.debug:
   msg: "{{ ec2_output }}"
 

