- name: create instance and r53 records
  hosts: all
  connection: local
  vars:
   sg_id: sg-05d7b78f97f2eb219
   ami_id: ami-0220d79f3f480ecf5
   domain_name: annuru.online
   environment: dev
   instances:
   - mongodb
   - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
     instance_type: "t3.micro"
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
     name: "{{ item }}-{{ environment }}"
     tags:
      Project: roboshop
      Component: "{{ item }}"
      Environment: "{{ environment }}"
      Name: "{{ item }}-{{ environment }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: create route 53
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ environment }}-{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"

  
 

