- name: shipping configure
  hosts:  shipping
  become: yes
  tasks:
  - name: install maven
    ansible.builtin.dnf:
      name: maven
      state: present

  - name: create systemuser for roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system user"

  - name: delete directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete the zip file
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: download te shipping code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip

  - name: unarchive zip file
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: clean the maven package
    ansible.builtin.command: mvn clean package
    args:
     chdir: /app 

  - name: rename the file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
     chdir: /app

  - name: copy the shipping service
    ansible.builtin.template:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: reload the shipping service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: install mysql client
    ansible.builtin.dnf:
      name: mysq
      state: present

  - name: check load shipping schemas
    ansible.builtin.shell: mysql -h '{{ MYSQL_HOST }}' -uroot -pRoboShop@1 < /app/db/schema.sql

  - name: create shipping app user
    ansible.builtin.shell: mysql -h "{{ MYSQL_HOST }}" -uroot -pRoboShop@1 < /app/db/app-user.sql 

  - name: loading shipping master data
    ansible.builtin.shell: mysql -h "{{ MYSQL_HOST }}" -uroot -pRoboShop@1 < /app/db/master-data.sql

  - name: start and enable shipping
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes